title: Gabriel Soyer
description: PhD Candidate, Political Science & International Affairs (UGA) · Comparative Politics · Political Economy · Environment
theme: minima
markdown: kramdown
permalink: pretty

# Simple top nav
header_pages:
  - about.md
  - publications.md
  - teaching.md